macro(add_option O DEF)
    if (DEFINED ${O})
        if (${${O}})
            set(${O} ON)
        else ()
            set(${O} OFF)
        endif()
    else ()
        set(${O} ${DEF})
    endif()
endmacro()

add_option(BUILD_SDF OFF)
add_option(BUILD_STATIC_LIBS OFF)

macro(print_config NAME)
message("")
message("------------------------------------------------------------------------")
message("-- Configuring ${NAME} ${PROJECT_VERSION}${VERSION_SUFFIX}")
message("------------------------------------------------------------------------")
message("-- CMake              Cmake version and location   ${CMAKE_VERSION} (${CMAKE_COMMAND})")
message("-- Compiler           C++ compiler version         ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message("-- TARGET_PLATFORM    Target platform              ${CMAKE_SYSTEM_NAME} ${ARCHITECTURE}")
message("-- BUILD_STATIC_LIBS  Build static lib             ${BUILD_STATIC_LIBS}")
message("-- BUILD_SDF          Build SDF HSM                ${BUILD_SDF}")
message("------------------------------------------------------------------------")
message("")
endmacro()